# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(db_column='password', max_length=128)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('0', '女')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'v_user',
            },
        ),
    ]
