# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-14 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grade',
            new_name='integral',
        ),
    ]
