# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-15 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190814_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
